#ifndef _APP_GSDML_MODULE_METADATA_H_
#define _APP_GSDML_MODULE_METADATA_H_

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <rtlabs/p-net/pnet_api.h>

#include "app_data.h"
#include "app_utils.h"
#include "app_gsdml.h"
#include "app_log.h"
#include "rtlabs/osal/osal.h"
#include "pnal.h"

#include "app_gsdml_utils.h"

#ifdef __cplusplus
extern "C" {
#endif

#define APP_GSDML_MOD_ID_METADATA 0x00000041

#define APP_GSDML_SUBMOD_ID_METADATA 0x00000141

#define APP_GSDML_PARAMETER_METADATA_IDX 126

#define APP_GSDML_INPUT_DATA_METADATA_SIZE 2
#define APP_GSDML_OUTPUT_DATA_METADATA_SIZE APP_GSDML_INPUT_DATA_METADATA_SIZE

#define APP_GSDML_SUBMOD_ID_METADATA_PARAMETERS_TABLE(_) \
\

APP_GSDML_SUBMOD_ID_METADATA_PARAMETERS_TABLE(GSDML_PARAMETER_DECLARE)

#define APP_GSDML_METADATA_SUBMODULES_TABLE(_) \
    _(submodule_metadata, "METADATA", APP_GSDML_API, PNET_DIR_IO, APP_GSDML_SUBMOD_ID_METADATA, APP_GSDML_INPUT_DATA_METADATA_SIZE, APP_GSDML_OUTPUT_DATA_METADATA_SIZE, APP_GSDML_SUBMOD_ID_METADATA_PARAMETERS_TABLE) \

APP_GSDML_METADATA_SUBMODULES_TABLE(GSDML_SUBMODULE_DECLARE)

GSDML_MODULE_DECLARE(APP_GSDML_MOD_ID_METADATA, module_metadata, "METADATA", APP_GSDML_METADATA_SUBMODULES_TABLE)

#ifdef __cplusplus
}
#endif

#endif