#ifndef _APP_GSDML_MODULE_DAP_H_
#define _APP_GSDML_MODULE_DAP_H_

#ifdef __cplusplus
extern "C" {
#endif

#include "app_gsdml_utils.h"
#include "app_gsdml.h"

#define PNET_SUBMOD_DAP_IDENT_PARAMETERS_TABLE(_)

#define PNET_SUBMOD_DAP_INTERFACE_1_IDENT_PARAMETERS_TABLE(_)

#define PNET_SUBMOD_DAP_INTERFACE_1_PORT_1_IDENT_PARAMETERS_TABLE(_)

#define PNET_SUBMOD_DAP_INTERFACE_1_PORT_2_IDENT_PARAMETERS_TABLE(_)

#define PNET_SUBMOD_DAP_INTERFACE_1_PORT_3_IDENT_PARAMETERS_TABLE(_)

#define PNET_SUBMOD_DAP_INTERFACE_1_PORT_4_IDENT_PARAMETERS_TABLE(_)

#define GSDML_DAP_SUBMODULES_TABLE(_)                                                                                                                                     \
    _(dap_identity_1, "DAP Identity 1", APP_GSDML_API, PNET_SUBMOD_DAP_IDENT, PNET_DIR_NO_IO, 0, 0, PNET_SUBMOD_DAP_IDENT_PARAMETERS_TABLE)                              \
    _(dap_interface_1, "DAP Interface 1", APP_GSDML_API, PNET_SUBMOD_DAP_INTERFACE_1_IDENT, PNET_DIR_NO_IO, 0, 0, PNET_SUBMOD_DAP_INTERFACE_1_IDENT_PARAMETERS_TABLE)     \
    _(dap_port_1, "DAP Port 1", APP_GSDML_API, PNET_SUBMOD_DAP_INTERFACE_1_PORT_1_IDENT, PNET_DIR_NO_IO, 0, 0, PNET_SUBMOD_DAP_INTERFACE_1_PORT_1_IDENT_PARAMETERS_TABLE) \
    _(dap_port_2, "DAP Port 2", APP_GSDML_API, PNET_SUBMOD_DAP_INTERFACE_1_PORT_2_IDENT, PNET_DIR_NO_IO, 0, 0, PNET_SUBMOD_DAP_INTERFACE_1_PORT_2_IDENT_PARAMETERS_TABLE) \
    _(dap_port_3, "DAP Port 3", APP_GSDML_API, PNET_SUBMOD_DAP_INTERFACE_1_PORT_3_IDENT, PNET_DIR_NO_IO, 0, 0, PNET_SUBMOD_DAP_INTERFACE_1_PORT_3_IDENT_PARAMETERS_TABLE) \
    _(dap_port_4, "DAP Port 4", APP_GSDML_API, PNET_SUBMOD_DAP_INTERFACE_1_PORT_4_IDENT, PNET_DIR_NO_IO, 0, 0, PNET_SUBMOD_DAP_INTERFACE_1_PORT_4_IDENT_PARAMETERS_TABLE)

PNET_SUBMOD_DAP_IDENT_PARAMETERS_TABLE(GSDML_PARAMETER_DEFINE)

PNET_SUBMOD_DAP_IDENT_PARAMETERS_TABLE(GSDML_PARAMETER_DEFINE)

PNET_SUBMOD_DAP_INTERFACE_1_PORT_1_IDENT_PARAMETERS_TABLE(GSDML_PARAMETER_DEFINE)

PNET_SUBMOD_DAP_INTERFACE_1_PORT_2_IDENT_PARAMETERS_TABLE(GSDML_PARAMETER_DEFINE)

PNET_SUBMOD_DAP_INTERFACE_1_PORT_3_IDENT_PARAMETERS_TABLE(GSDML_PARAMETER_DEFINE)

PNET_SUBMOD_DAP_INTERFACE_1_PORT_4_IDENT_PARAMETERS_TABLE(GSDML_PARAMETER_DEFINE)

GSDML_DAP_SUBMODULES_TABLE(GSDML_SUBMODULE_DECLARE)

GSDML_MODULE_DECLARE(PNET_MOD_DAP_IDENT, dap_1, "DAP 1", GSDML_DAP_SUBMODULES_TABLE)

#ifdef __cplusplus
}
#endif

#endif