/*
 * This source file was generated by the Gradle 'init' task
 */
package com.nit.profinet;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class ISO15745ProfileTest {
}
