#ifndef _NIT_EMBEDDED_CLAMIR_DRIVER_FRAMEBUFFER_CORE_FIELD_TABLE_H_
#define _NIT_EMBEDDED_CLAMIR_DRIVER_FRAMEBUFFER_CORE_FIELD_TABLE_H_

#include <cinttypes>

typedef enum nit_framebuffer_core_operating_mode_enum
{
    NIT_FRAMEBUFFER_CORE_OPERATING_MODE_NORMAL,
    NIT_FRAMEBUFFER_CORE_OPERATING_MODE_TEST_PATTERN_BALL,
    NIT_FRAMEBUFFER_CORE_OPERATING_MODE_TEST_UNIFORM_SHUTTER_CLOSED,
    NIT_FRAMEBUFFER_CORE_OPERATING_MODE_TEST_UNIFORM_SHUTTER_OPEN,
    NIT_FRAMEBUFFER_CORE_OPERATING_MODE_EMPTY,
    NIT_FRAMEBUFFER_CORE_OPERATING_MODE_MAX,
} nit_framebuffer_core_operating_mode_t;

#define NIT_FRAMEBUFFER_CORE_FIELD_TABLE(_)                               \
    _(framebuffer_core, operating_mode, uint16_t, sizeof(uint16_t), 0)        \

#endif