nit_pwm_core_pwm_limit_max_set: nit_pwm_core_pwm_limit_max_offset (49152): 1117
nit_pwm_core_pwm_limit_min_set: nit_pwm_core_pwm_limit_min_offset (49155): 372
nit_mom_core_start_track_mom_t_set: nit_mom_core_start_track_mom_t_offset (16393): 40
nit_mom_core_end_of_track_set: nit_mom_core_end_of_track_offset (16400): 30
nit_mom_core_mode_set: nit_mom_core_mode_offset (16395): 2
nit_mom_core_reference_track_set: nit_mom_core_reference_track_offset (16399): 3
nit_mom_core_time_track_low_set: nit_mom_core_time_track_low_offset (16396): 200000000
nit_mom_core_time_track_high_set: nit_mom_core_time_track_high_offset (16397): 0
nit_mom_core_threshold_set: nit_mom_core_threshold_offset (16384): 1182
nit_roi_core_round_set: nit_roi_core_round_offset (32772): 0
nit_gen_core_enable_roi_set: nit_gen_core_enable_roi_offset (2): 1
nit_roi_core_x1_set: nit_roi_core_x1_offset (32768): 9
nit_roi_core_x2_set: nit_roi_core_x2_offset  (32770): 53
nit_roi_core_y1_set: nit_roi_core_y1_offset  (32769): 8
nit_roi_core_y2_set: nit_roi_core_y2_offset  (32771): 52
nit_gen_core_digital_out_conf_set: nit_gen_core_digital_out_conf_offset (11): 0
control_unit_core_black_level_set: nit_control_unit_core_black_level_offset (36): 1000
control_unit_core_bias_v_set: nit_control_unit_core_bias_v_offset (1): 13652
control_unit_core_int_time_set: nit_control_unit_core_int_time_offset (0): 600
control_unit_core_drift_enable_set: nit_control_unit_core_drift_enable_offset (16): 1
control_unit_core_drift_position_set: nit_control_unit_core_drift_position_offset (17): 14
nit_gen_core_change_op_mode_set: nit_gen_core_change_op_mode_offset (5): 1
control_unit_core_bpc_en_set: nit_control_unit_core_bpc_en_offset (5): 1