intensity_min 0
intensity_max 0
mom_00 0
mom_01 0
mom_10 0
mom_11 0
mom_02 0
mom_20 0
start_track_mom_t 40
track_nbr 0
mode 1
time_track_low 0
time_track_high 0
frame_max 0
reference_track 0
end_of_track 0