#!/usr/bin/env python

import numpy as np
import argparse
import os, sys

parser = argparse.ArgumentParser()

parser.add_argument('-v', "--value", help="value", type=float, default=0)
parser.add_argument('-o', "--output", help="output file")

args = parser.parse_args()

if args.value == None:
    parser.print_help()
    exit(1)

scale = (float(args.value) * np.ones((64, 64))).astype(dtype=np.int32)

if args.output:
    with open(args.output, "wb") as f:
        scale.tofile(f)
        exit(0)

else:
    buffer = scale.tobytes()
    os.write(sys.stdout.fileno(), buffer)
    exit(0)