#!/usr/bin/env python

import numpy as np
import argparse
import os, sys
import mmap

parser = argparse.ArgumentParser()

parser.add_argument('-f', "--file", help="input file")

args = parser.parse_args()

if args.file == None:
    parser.print_help()
    exit(1)

if not os.path.exists(args.file) or os.path.isfile(args.file):
    print("ERROR: file doesn't exists or not a file")
    parser.print_help()
    exit(1)

with open("/dev/mem", mode="wb") as fd:
    with mmap.mmap(fd, 0x00004000, flags=mmap.MAP_SHARED, prot=mmap.PROT_READ | mmap.PROT_WRITE, access= mmap.ACCESS_DEFAULT, offset=0x48000000, trackfd=True) as mm:
        with open(args.path.file, "r") as f:
            buffer = f.read()
            mm.write(buffer)