#!/usr/bin/env python

import numpy as np
import argparse
import os, sys

parser = argparse.ArgumentParser()

parser.add_argument('-v', "--value", help="value", type=float, default=1)
parser.add_argument('-o', "--output", help="output file")

args = parser.parse_args()

if args.value == None:
    parser.print_help()
    exit(1)

scale = np.ones((64, 64))

scale[:, 0:8]    = 0.001
scale[:, 8:16]   = 0.01
scale[:, 16:24]  = 0.1
scale[:, 24:32]  = 1.0
scale[:, 32:40]  = 10.0
scale[:, 40:48]  = 100.0
scale[:, 48:56]  = 1000.0
scale[:, 56:64]  = 10000.0

scale = (float(args.value) * scale).astype(dtype=np.int32)


if args.output:
    with open(args.output, "wb") as f:
        scale.tofile(f)
        exit(0)

else:
    buffer = scale.tobytes()
    os.write(sys.stdout.fileno(), buffer)
    exit(0)